import { Model } from '@nozbe/watermelondb';
import { text, field, date, json } from '@nozbe/watermelondb/decorators';

const sanitizeStringList = (raw: any): string[] => {
    return Array.isArray(raw) ? raw : [];
}

export default class Playlist extends Model {
    static table = 'playlists';

    @text('playlist_id') playlistId!: string;
    @text('name') name!: string;
    @text('description') description?: string;
    @text('user_id') userId!: string;

    @json('song_ids_json', sanitizeStringList) songIds!: string[];

    @field('auto_generated') autoGenerated?: boolean;
    @field('is_public') isPublic?: boolean;

    @date('created_at') createdAt!: Date;
    @date('updated_at') updatedAt?: Date;
}
